init changes
electrumpayments/money-transfer-retailer-interface pull request #54
Opened 2021-02-10 10:06 UTC by MNS003

Hey there,

Here's the changes necessary to support Bulk Order Lookups and Pin Update requests through the money transfer interface. Lemme know what you think.

2021-02-10 12:54 UTC, PatrickColborne commented
Minenhle please upgrade this to build on Java 11.

2021-02-10 14:20 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +   public final void lookupOrders(
Sonar is not happy with this method and recommends having a payload instead of having so many query params. And I'm inclined to agree. But this is a GET 😞  Would welcome a suggestion.

2021-02-12 11:27 UTC, Keelan-Moore requested changes

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Identifies the institution from which the transaction originates. Value to be assigned by Electrum.") @QueryParam(LookupOrders.QueryParameters.ORIGINATOR_INST_ID) String o
This reads a little funny? Maybe its the from which from where thing? Like

```Identifies the institution from where the transaction originates. Value to be assigned by Electrum.```

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Should be among the options of the OrderStatus in SendCash") @QueryParam(LookupOrders.QueryParameters.STATUS) String status,
This isn't horribly helpful, 

Imagine you're a Byte Orbit dev implementing this API, where in hell are you going to get the list of OrderStatus's?

Look at something like this https://electrumpayments.github.io/airtime-service-interface-docs/specification/definitions/#purchaseconfirmation

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The max number of expected responses.") @QueryParam(LookupOrders.QueryParameters.LIMIT) String limit,
The maximum number

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +            limit,
I would put the limit and offset at the bottom

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The max number of expected responses.") @QueryParam(LookupOrders.QueryParameters.LIMIT) String limit,
look at our other apis that include limit and offset, maybe mention they are for paging

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +      public static final String LOOKUP_ORDERS = "lookupOrders";
As per the spec this should be ```getCustomerOrderHistory``` right?

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/IAdminResource.java
> +         String customerProfileId,
also notnull

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/OrdersResource.java
> +      }
whats this doing?

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/OrdersResource.java
> +   @ApiOperation(value = UpdateOrderPin.UPDATE_ORDER_PIN, notes = "Request to set the order's redemption pin to a new value", response = MoneyTransferOrderPinUpdateRequest.class, authorizations = {
I think as PIN is an acronym, it should be capitalised.

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/model/MoneyTransferOrderPinUpdateRequest.java
> +@ApiModel(description = "Used to update the pin on a order.")
Same as other PIN comment.

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/model/MoneyTransferOrderPinUpdateRequest.java
> +   @ApiModelProperty(value = "Reference used by the service provider to uniquely identify the money transfer order on their system. This field can be used if the provider supplies a supplementary ref
Shew... this is long haha but I can see you've copied it from elsewhere so guess there is precedent for it haha

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +   public final void lookupOrders(
yeah, i feel i'd rather stick with the semantically correct ```GET``` rather than shoving a```POST``` where it doesn't fit

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +   public final void lookupOrders(
https://softwareengineering.stackexchange.com/questions/353086/what-is-a-proper-way-to-do-a-complex-restful-search-method

2021-02-12 11:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +   public final void lookupOrders(
I liked this blog a lot. Shaped a lot of my thinking about REST apis 

https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

2021-02-12 15:18 UTC, MNS003 commented on pom.xml
> +    <patch-version>0-SNAPSHOT</patch-version>
Done

2021-02-12 15:19 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         private QueryParameters(){}
To hide implicit no args ctor. Circle doesn't like that.

2021-02-12 15:20 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +      public static final String FULL_PATH = AdminResource.PATH + RELATIVE_PATH;
Done.

2021-02-12 15:21 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         public static final String OFFSET = "offset";
Lit. Thanks. I missed that.

2021-02-12 15:22 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiResponse(code = OrdersResource.LookupOrder.SUCCESS, message = "OK", response = MoneyTransferCustomerOrderHistory.class),
Thank you!

2021-02-12 15:25 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         public static final String TO_DATETIME = "toDateTime";
I thought of that but then decided on this because it implies that this will be a datetime object in string form. I'm not married to the idea and it does seem odd. But for the sake of giving hints I decided to use this. 🤔 I think I'll got with `FROM_DATE_TIME`. Seems more natural.

2021-02-12 15:27 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Identifies the institution from which the transaction originates. Value to be assigned by Electrum.") @QueryParam(LookupOrders.QueryParameters.ORIGINATOR_INST_ID) String o
Will, will try where. I get your point. Though this is a copy paste. Should I update the others?

2021-02-12 15:40 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The max number of expected responses.") @QueryParam(LookupOrders.QueryParameters.LIMIT) String limit,
Hmm, could not find one in the public apis. Could you give an example to look at.

2021-02-12 15:41 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +            limit,
Hmm, I put the receiver there coz it was the only required one. But I guess it's not that deep.

2021-02-12 15:42 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +      public static final String LOOKUP_ORDERS = "lookupOrders";
That is exactly what it should be. I knew missed something like this.

2021-02-12 15:43 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/OrdersResource.java
> +      }
Keeping Sonar happy, lol. It's "removing" the implicit no args constructor. Should I remove?

2021-02-12 15:44 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/OrdersResource.java
> +   @ApiOperation(value = UpdateOrderPin.UPDATE_ORDER_PIN, notes = "Request to set the order's redemption pin to a new value", response = MoneyTransferOrderPinUpdateRequest.class, authorizations = {
Hmm, interesting.

2021-02-12 15:44 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/OrdersResource.java
> +   @ApiOperation(value = UpdateOrderPin.UPDATE_ORDER_PIN, notes = "Request to set the order's redemption pin to a new value", response = MoneyTransferOrderPinUpdateRequest.class, authorizations = {
Done.

2021-02-12 15:45 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/model/MoneyTransferOrderPinUpdateRequest.java
> +@ApiModel(description = "Used to update the pin on a order.")
Done.

2021-02-12 15:45 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/model/MoneyTransferOrderPinUpdateRequest.java
> +   @ApiModelProperty(value = "Reference used by the service provider to uniquely identify the money transfer order on their system. This field can be used if the provider supplies a supplementary ref
Lol, I tried copying as much as possible 😆

2021-02-12 15:46 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/IAdminResource.java
> +         String customerProfileId,
Done.

2021-02-16 08:02 UTC, Keelan-Moore requested changes

2021-02-16 08:02 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Identifies the service provider to whom this request must be directed.", required = true) @QueryParam(LookupOrders.QueryParameters.RECEIVER_ID) @NotNull String receiverId,
I think the required params should be first on the list.  Maybe bump this one up to customerProfileId

2021-02-16 08:02 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Uniquely identifies customer's profile on the upstream entity's system.") @QueryParam(LookupOrders.QueryParameters.CUSTOMER_PROFILE_ID) String customerProfileId,
this should be not null

2021-02-16 09:11 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The max number of expected responses.") @QueryParam(LookupOrders.QueryParameters.LIMIT) String limit,
Done. Thanks!

2021-02-16 09:13 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The offset from the beginning date.") @QueryParam(LookupOrders.QueryParameters.OFFSET) String offset,
I had assumed it was the date offset. Number of orders makes more sense I guess.

2021-02-16 09:15 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
>           @ApiParam(value = "Should be among the options of the OrderStatus in SendCash") @QueryParam(LookupOrders.QueryParameters.STATUS) String status,
This will change to be a reference to the StatusEnum of MT lookup resonse.

2021-02-16 09:16 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Identifies the service provider to whom this request must be directed.", required = true) @QueryParam(LookupOrders.QueryParameters.RECEIVER_ID) @NotNull String receiverId,
Done.

2021-02-16 09:16 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Uniquely identifies customer's profile on the upstream entity's system.") @QueryParam(LookupOrders.QueryParameters.CUSTOMER_PROFILE_ID) String customerProfileId,
Done.

2021-02-17 11:15 UTC, Keelan-Moore requested changes

2021-02-17 11:15 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +      private GetCustomerOrderHistory(){}
Can you run formatter to clear these kinda things up?

2021-02-17 11:15 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The max number of expected responses.") @QueryParam(GetCustomerOrderHistory.QueryParameters.LIMIT) int limit,
You seemed to have missed this comment - I think the description should be

'A limit on the number of orders to be returned.'

2021-02-17 11:15 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The offset for the number of orders.") @QueryParam(GetCustomerOrderHistory.QueryParameters.OFFSET) int offset,
I think you also missed this comment - I think the description should be 

'The number of orders to skip before starting to collect the result set.'

2021-02-17 11:15 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +   @GET
You don't have an` @path` annotation here

2021-02-17 11:15 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/model/MoneyTransferCustomerOrderHistory.java
> +   private List<MoneyTransferLookupResponse> orders = null;
It seems in the spec this was supposed to be an order object? not a list of MTLookupResponses

2021-02-17 11:17 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +      private GetCustomerOrderHistory(){}
Issue is that the formatter will move definitions to the bottom.

2021-02-17 11:18 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The max number of expected responses.") @QueryParam(GetCustomerOrderHistory.QueryParameters.LIMIT) int limit,
Oh lit sorry. Done.

2021-02-17 11:19 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "The offset for the number of orders.") @QueryParam(GetCustomerOrderHistory.QueryParameters.OFFSET) int offset,
Hmm, better description, thanks 👌

2021-02-17 11:21 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +   @GET
Thank you!

2021-02-17 11:22 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/model/MoneyTransferCustomerOrderHistory.java
> +   private List<MoneyTransferLookupResponse> orders = null;
Oh, no. That was changed. I think David left before he could write that out. But basically the Order object he was proposing had a subset of the fields in MTLookupResponse so we changed it to be the whole object.

2021-02-17 14:27 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +      private GetCustomerOrderHistory(){}
It doesn't if you change the settings. 

You should have Optimised inputs and Code cleanup checked but don't have rearrange code checked.

2021-02-18 07:09 UTC, Keelan-Moore requested changes

2021-02-18 07:09 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +   // MNS TODO: Find a more dynamic way to list Enums. See status and paymentType
Please remove

2021-02-18 07:09 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Should be among the options of the Money Transfer Order Statuses: [UNREDEEMED, REDEEMED, CANCELLED, EXPIRED, ON_HOLD, UNCONFIRMED]") @QueryParam(GetCustomerOrderHistory.Qu
Revert to not stating explicitly

2021-02-18 08:24 UTC, Keelan-Moore requested changes

2021-02-18 08:24 UTC, Keelan-Moore commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Payment identifier name for the payment type indicated. Required if 'paymentType' is defined.") @QueryParam(GetCustomerOrderHistory.QueryParameters.PAYMENT_IDENTIFIER_NAME
Maybe change this back to just `Payment identifier  for the payment type indicated` rather than `Payment identifier name .... ` 

As some systems may use an id, some may use names or enums or whatevs.

2021-02-18 11:05 UTC, Keelan-Moore approved these changes
🥳🥳🥳

2021-02-18 14:04 UTC, merged