init changes
electrumpayments/money-transfer-retailer-interface pull request #57
Opened 2021-07-13 15:40 UTC by MNS003

2021-07-13 16:03 UTC, francoisdavel requested changes
Hey Mini, may you make one more change and that is to make the Originator in the `MoneyTransferCustomerOrderHistory` nullable (So just remove the @NotNull annotation)

2021-07-13 16:03 UTC, francoisdavel commented on src/docs/devguide/hugo/site/content/release-notes.md
> +- Added `offset` and `limit` to `getCustomerOrderHistory`'s query parameters.
```suggestion
- Added `offset` and `limit` to `getCustomerOrderHistory`'s query parameters.
- Made `originator` optional in the `getCustomerOrderHistory` response payload `MoneyTransferCustomerOrderHistory`
```

2021-07-13 16:03 UTC, francoisdavel commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +            receiverId,
What happened here?

2021-07-13 17:04 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +            receiverId,
There was an argument mismatch. The order of the arguments changed. This is the only place where the argument order is like this. This did not seem to affect anything because the inlet uses the `UriInfo` for the query params but it was still a hidden bug.

2021-07-13 17:05 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/api/AdminResource.java
> +         @ApiParam(value = "Offset the entire result set by this amount of top-ordered results. Use in conjunction with the \"limit\" parameter to tune which subset of the entire result set (as const
Done

2021-07-13 17:06 UTC, MNS003 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 18 February 2021
Done

2021-07-13 18:57 UTC, francoisdavel commented
Hey Minenhle we need to add the paging info to the `MoneyTransferCustomerOrderHistory` model too so Nedbank can use the paging query parameters correctly

2021-07-14 07:29 UTC, francoisdavel requested changes
LGTM, just some minor comments to remove and a misalignment with validation.

2021-07-14 07:29 UTC, francoisdavel commented on pom.xml
> +    <patch-version>0-SNAPSHOT</patch-version>
```suggestion
    <patch-version>0</patch-version>
```

2021-07-14 07:29 UTC, francoisdavel commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 13 Jul 2021
```suggestion
Released 14 July 2021
```

2021-07-14 07:29 UTC, francoisdavel commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Pattern(regexp = ".{0,2083}") // If it's good enough for Internet Explorer then it's good enough for me!
```suggestion
   @Pattern(regexp = ".{0,2083}")
```

2021-07-14 07:29 UTC, francoisdavel commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Pattern(regexp = ".{0,2083}") // If it's good enough for Internet Explorer then it's good enough for me!
```suggestion
   @Pattern(regexp = ".{0,2083}")
```

2021-07-14 07:29 UTC, francoisdavel commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Pattern(regexp = ".{0,2083}") // If it's good enough for Internet Explorer then it's good enough for me!
```suggestion
   @Pattern(regexp = ".{0,2083}")
```

2021-07-14 07:29 UTC, francoisdavel commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Pattern(regexp = ".{0,256}") // Probably won't ever be bigger than that...
```suggestion
   @Pattern(regexp = ".{0,256}") 
```

2021-07-14 07:29 UTC, francoisdavel commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Min(0)
Here is a misalignment the comment says 1 and the code says 0. Which is it?

```suggestion
    * minimum: 1
    *
    * @return nrRecords
    **/
   @JsonProperty("nrRecords")
   @ApiModelProperty(value = "The total number of records in this search")
   @Min(0)
```

2021-07-14 07:44 UTC, MNS003 commented on pom.xml
> +    <patch-version>0-SNAPSHOT</patch-version>
Done

2021-07-14 07:57 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Min(0)
Done. It's 0.

2021-07-14 07:57 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Pattern(regexp = ".{0,256}") // Probably won't ever be bigger than that...
Done.

2021-07-14 07:57 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Pattern(regexp = ".{0,2083}") // If it's good enough for Internet Explorer then it's good enough for me!
Done.

2021-07-14 07:57 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Pattern(regexp = ".{0,2083}") // If it's good enough for Internet Explorer then it's good enough for me!
Done.

2021-07-14 07:57 UTC, MNS003 commented on src/main/java/io/electrum/moneytransfer/model/PaginationInfo.java
> +   @Pattern(regexp = ".{0,2083}") // If it's good enough for Internet Explorer then it's good enough for me!
Done.

2021-07-14 07:57 UTC, MNS003 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 13 Jul 2021
Done.

2021-07-14 10:07 UTC, francoisdavel approved these changes
LGTM

2021-07-14 10:07 UTC, francoisdavel commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 14 Jul 2021
```suggestion
Released 14 July 2021
```

2021-07-14 10:14 UTC, MNS003 commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released 14 Jul 2021
Done.

2021-07-14 10:15 UTC, merged