Adding idNumber and idType to OrderLookup
electrumpayments/money-transfer-retailer-interface pull request #62
Opened 2022-08-30 10:17 UTC by LynnElectrum

- Adding IdType and IdNumber query parameter
- Adding "OTHER" enum to IdType
- Feature so Minor version bump

2022-09-16 10:55 UTC, MikeField119 requested changes
Couple of small changes from my side, otherwise looks pretty good. I've asked @TimElectrum to have a look as well.
Thanks for all the effort with the testing!

2022-09-16 10:55 UTC, MikeField119 commented on pom.xml
> +    <hibernate-validator-version>5.4.3.Final</hibernate-validator-version>
Commenting here just because I can't above.
I don't think we need to bump the `service-interface-base-version` since we didn't change any of the models which inherit from here.
We should double check this with an API guru though.

2022-09-16 10:55 UTC, MikeField119 commented on pom.xml
> +    <hibernate-validator-version>5.4.3.Final</hibernate-validator-version>
@TimElectrum

2022-09-16 11:32 UTC, TimElectrum reviewed
happy enough. Just some small things but I'm happy for Mike to give the okay once they're addressed. Or you're welcome to send it back to me

2022-09-16 11:32 UTC, TimElectrum commented on pom.xml
> +    <hibernate-validator-version>5.4.3.Final</hibernate-validator-version>
it's good practice to bump the base API as you go along. Otherwise it's one day forced to go through a large version change and then a bunch unexpected issues crop up.

As much time as you may have spent on this already, encountering a few small issues as you go is much better than encountering all those same issues all at once in future.

Keep an eye out for any breaking changes which may have snuck into the base API (i.e. comments in the release notes which mention breaking changes even if the major version didn't change).

2022-09-16 11:32 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +- Added `idNumber` and `idType` to `lookupOrder`'s query parameters.
pre-emptive comment:

when you bump the base API, please list the changes introduced by the bump here (You can basically copy/paste the release notes entries). The reason is that the base API's release notes aren't publicised so _these_ release notes would actually be the first time those changes are made public.

2022-09-16 11:32 UTC, TimElectrum commented on src/main/java/io/electrum/moneytransfer/model/IdType.java
> +   OTHER("OTHER");
what's the difference between `UNKNOWN` and `OTHER`?

The point of all of these is that they tell what the identifier is so that you can look it up correctly e.g. don't go looking in the list of national ID numbers if you've been given a passport number.

But if the `idType` is `OTHER` - well that's a pretty broad group. So broad as to be almost meaningless, no?

What does `OTHER` tell us that `UNKOWN` doesn't?

2022-09-16 11:32 UTC, TimElectrum commented on src/test/java/io/electrum/moneytransfer/models/NewModelTests.java
> +package io.electrum.moneytransfer.models;
tbh - I haven't gone over the tests with a fine-toothed comb. You didn't really change any of the models so I'm happy enough that you didn't breaking them in this PR

2022-09-16 11:32 UTC, TimElectrum commented on src/test/java/io/electrum/vas/api/TestMoneyTransferApiInterfaces.java
> +            {IOrdersResourceTestImpl.class,"lookupOrder"},
I wonder if you should exclude the `lookupOrder` operation/method because of its weird edge case situation

2022-09-16 11:32 UTC, TimElectrum commented on src/test/java/io/electrum/vas/api/TestMoneyTransferApiResourceClasses.java
> +         {OrdersResourceTestClass.class, "lookupOrder", IOrdersResource.class, "lookupOrder"},
again, maybe this operation/method should be dropped

2022-09-16 11:49 UTC, LynnElectrum commented on src/test/java/io/electrum/vas/api/TestMoneyTransferApiInterfaces.java
> +            {IOrdersResourceTestImpl.class,"lookupOrder"},
the lookupOrder didnt have an edge case I believe. are you referring to getFeeQuotes?

2022-09-19 10:27 UTC, MikeField119 approved these changes
LGTM, I'm going to make 2 tiny updates to the README and release notes, and ask @TimElectrum for a last review and to resolve his comments.

2022-09-19 10:37 UTC, TimElectrum approved these changes
LGTM

2022-09-19 10:43 UTC, merged